# Generated by Django 5.2.4 on 2025-07-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trading',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_car', models.CharField(max_length=100)),
                ('fecha_creacion_car', models.DateField()),
            ],
        ),
    ]
